### ISSUE TITLE
Remove dependency on curl

### ISSUE THREAD

**Issue by analogic** [analogic/lescript#21]
(https://github.com/analogic/lescript/pull/18#issuecomment-239614537) Was wondering why there needs to be a dependency on curl or some other HTTP client in the first place.
Not possible to just use the standard PHP https stream wrapper?

**Comment by peter279k** [comment]
Hi @analogic , I think it's possible to only use the PHP cURL stream wrapper.
For example, some people want to use Composer and ```Guzzle``` which is based on cURL because this library let us access easily http request and response.
I use both ```Guzzle``` and cURL library and I think using cURL library is easy to deploy to the shared hosting. Perhaps you can create another branch for someone who want to use Guzzle or other HTTP client library based on PHP cURL stream wrapper 👍 .
